### ISSUE TITLE
POV function does not work in some places

### ISSUE THREAD

**Issue by noidcreid** [IllusionMods/KeelPlugins#27]
Hello, I would like to ask if there is known issues where POV does not work in some places. So I downloaded Koikatsu Betterrepacked RX10.1, and I believe RealPOV plugin is in it. And I found out that in some places in story mode like Koikatsu club and Home, the POV function with default key "backspace" doesn't work. I did try the RealPOV function and it works in rooftop, corridor, infirmary, and Japanese style room (some places where I've tried the POV in)

Idk if this is the right error log, but I think it might be it
[Error  : Unity Log] NullReferenceException
Stack trace:
bool RealPOV.Koikatu.RealPOV.ApplyRotation(NeckLookControllerVer2)

Please help..

**Comment by ManlyMarco** [comment]
Should be fixed now. That being said, it's still going to be fairly flaky since it's not intended to be using in the roam mode, you should use the built-in POV mode by pressing space instead.
