### ISSUE TITLE
'Vignette' saved setting failing to load

### ISSUE THREAD

**Issue by ghost** [IllusionMods/KeelPlugins#29]
Set vignette to 'off' and saved the parameters.

1. Restarting studio, vignette is back to 'on';

2. Using the 'reset' scene button also reverts it back to 'on'.

Using the load parameters button does set vignette to 'off' now, and of course whatever setting it's on and saved with a scene, on scene load it works correctly. For testing purposes I've also tried the same thing with shadow types, which worked correctly in all cases.
Is this the intended behavior or a possible bug? Game is Koikatsu JP version, DefaultParamEditor.Koikatu plugin v.1.1.2.268

**Comment by ManlyMarco** [comment]
Appears to be fixed by now.
