### ISSUE TITLE
CharaStateX hard lock

### ISSUE THREAD

**Issue by Coppersocket** [IllusionMods/KeelPlugins#34]
So, as this is a relatively new feature I can understand why this problem occurs. But with MoreOutfits.dll now being a thing it has a severe incompatibility with CharaStateX, where if you have a character wearing a outfit that is in a coord slot that's been created by MoreOutfits and then sub select a character that does not have that many outfits will grind the entire studio to a halt and end up in a feedback loop where it attempts to repeatedly load data that isn't there.

This can severely negatively impact your entire computer as it'll quickly eat all your ram if you're not fast enough to close it down. I imagine on lower end machines it has a very real risk of freezing their entire computers.

**Comment by ManlyMarco** [comment]
Seems to have been fixed at some point, can't reproduce.
