### ISSUE TITLE
DefaultParamEditor - Joint corrections not saving

### ISSUE THREAD

**Issue by Iodoy** [IllusionMods/KeelPlugins#36]
When changing the joint corrections status (on/off) and trying to save the changes arent kept 
and default to always off, from what Ive been told they should be able to be changed.
This was checked with the lastest build made on May 2022
Attached are the config file and a outputlog from the session where the attempt was made

[output_log.txt](https://github.com/IllusionMods/KeelPlugins/files/9759919/output_log.txt)
[DefaultParamEditorData.txt](https://github.com/IllusionMods/KeelPlugins/files/9759922/DefaultParamEditorData.txt)

**Comment by AgiShark** [comment]
I don't think the plugin has ever saved parameters related to joint correction. e.g. expression stuff

**Comment by Iodoy** [comment]
Was talking to marco the other day and its supossed to save the joint corrections, was also asked by him to post the issue

**Comment by AgiShark** [comment]
I understand. But my opinion remains the same

**Comment by ManlyMarco** [comment]
Turns out DefaultParamEditor never handled joint correction. I restored the feature in KKUS to fix this issue, it'll be included in next release. https://github.com/IllusionMods/HSPlugins/commit/ce12c8fe31a13ce8dabe1cdf68d75204ec35c43b
