### ISSUE TITLE
'Load Scene Param' never loads Shade 2

### ISSUE THREAD

**Issue by fwgb** [IllusionMods/KeelPlugins#38]
![Untitled](https://user-images.githubusercontent.com/126597144/221913121-6257e419-2318-4ea9-b4c0-2fbc71c222bb.png)

When clicking Load Scene Param, all settings will load except for Shade 2 which stays at its old value.

If this is the wrong place to report this bug then please suggest where to report it, because this one really bothers me. I like to press Load Scene Param on scenes made by other people, but this bug means things never look as they should.

**Comment by ManlyMarco** [comment]
That option is added by a plugin <https://github.com/IllusionMods/KK_Plugins/#twolut>
Not sure what to do about it.
