### ISSUE TITLE
RealPOV works in PlayHome but not Studio [RealPOV.PlayHome.dll]

### ISSUE THREAD

**Issue by Riepr** [IllusionMods/KeelPlugins#43]
Is this intended? I would be so sad if it's true.

Using Backspace works in PlayHome, I have toggled Female POV using F1, and it works perfectly in the standard game... 
**but it pressing Backspace does nothing inside the PlayHomeStudio64bit.**

This plugin is insanely cool, but I cannot create anything new or custom scenes unless I can also toggle the POV inside the studio. I would really appreciate the help!

**Comment by Riepr** [comment]
@FrostedAshe  I know it's two years late, but is RealPOV supported inside the Studio? Backspace does nothing in studio sadly. Am I missing something here?

**Comment by ManlyMarco** [comment]
RealPOV supports studio in KK and KKS only.
